server:
  image:
    repository: prom/prometheus
    tag: v2.33.5
    pullPolicy: IfNotPresent
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: false
pushgateway:
  enabled: false
